// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBf0KxKrKjDImRbBe_W9LnJYdGRPu5eqY',
    appId: '1:141030912906:android:6ed8f39dd7cb2100bc0e73',
    messagingSenderId: '141030912906',
    projectId: 'smartmenu-d3e47',
    storageBucket: 'smartmenu-d3e47.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBf0KxKrKjDImRbBe_W9LnJYdGRPu5eqY',
    authDomain: 'smartmenu-d3e47.firebaseapp.com',
    projectId: 'smartmenu-d3e47',
    storageBucket: 'smartmenu-d3e47.appspot.com',
    messagingSenderId: '141030912906',
    appId: '1:141030912906:web:f3200a5d9610ca88bc0e73',
    measurementId: 'G-YZLRJBVD5V',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1qwFcQCCLgXGeP96srL8H1W0yOoKMcvg',
    appId: '1:141030912906:ios:8e99d108b0221148bc0e73',
    messagingSenderId: '141030912906',
    projectId: 'smartmenu-d3e47',
    storageBucket: 'smartmenu-d3e47.appspot.com',
    androidClientId: '141030912906-n8l3ac9gvgafvoujbt8fis2svrbbgbh1.apps.googleusercontent.com',
    iosClientId: '141030912906-ih9blc7g1f3fefuslh73h6lagpiff2cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartMenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1qwFcQCCLgXGeP96srL8H1W0yOoKMcvg',
    appId: '1:141030912906:ios:8e99d108b0221148bc0e73',
    messagingSenderId: '141030912906',
    projectId: 'smartmenu-d3e47',
    storageBucket: 'smartmenu-d3e47.appspot.com',
    androidClientId: '141030912906-n8l3ac9gvgafvoujbt8fis2svrbbgbh1.apps.googleusercontent.com',
    iosClientId: '141030912906-ih9blc7g1f3fefuslh73h6lagpiff2cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartMenu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBf0KxKrKjDImRbBe_W9LnJYdGRPu5eqY',
    appId: '1:141030912906:web:e8d4052ad8155251bc0e73',
    messagingSenderId: '141030912906',
    projectId: 'smartmenu-d3e47',
    authDomain: 'smartmenu-d3e47.firebaseapp.com',
    storageBucket: 'smartmenu-d3e47.appspot.com',
    measurementId: 'G-GJKZPDHDQZ',
  );
}
